// Expanded skill catalogue (~296 skills). Idempotent (upserts). Run by the
// "Seed database" GitHub workflow after seed.ts, or locally via npx tsx.
import 'dotenv/config'
import { PrismaClient } from '@prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! })
const db = new PrismaClient({ adapter })

/**
 * Expand the skills catalogue by ~10x. Idempotent via upsert — re-runs
 * won't duplicate rows. Existing categories are kept; three new ones
 * (Hands-on / Trades, Health & Wellbeing, Education) are added for the
 * kinds of work community sustainability projects actually need.
 *
 *   npm run db:apply  (then) tsx prisma/seed-skills-expanded.ts
 * or invoke directly with ts-node — see the existing one-off seed files.
 */

const skills: Array<{ name: string; category: string }> = [
  // ─── Technical ─────────────────────────────────────────────
  { name: 'Data visualisation', category: 'Technical' },
  { name: 'Database design', category: 'Technical' },
  { name: 'API design', category: 'Technical' },
  { name: 'Open data publishing', category: 'Technical' },
  { name: 'IoT / sensor networks', category: 'Technical' },
  { name: 'LoRaWAN / mesh networking', category: 'Technical' },
  { name: 'Air-quality sensor deployment', category: 'Technical' },
  { name: 'Energy modelling', category: 'Technical' },
  { name: 'CAD / 3D modelling', category: 'Technical' },
  { name: 'BIM (Building Information Modelling)', category: 'Technical' },
  { name: 'Arduino / embedded prototyping', category: 'Technical' },
  { name: 'Raspberry Pi tinkering', category: 'Technical' },
  { name: 'Remote sensing / satellite imagery', category: 'Technical' },
  { name: 'LiDAR processing', category: 'Technical' },
  { name: 'QGIS', category: 'Technical' },
  { name: 'OpenStreetMap editing', category: 'Technical' },
  { name: 'KoboToolbox / ODK survey design', category: 'Technical' },
  { name: 'R / statistical computing', category: 'Technical' },
  { name: 'Python scripting', category: 'Technical' },
  { name: 'SQL', category: 'Technical' },
  { name: 'Spreadsheet modelling', category: 'Technical' },
  { name: 'Workflow automation (Zapier / n8n)', category: 'Technical' },
  { name: 'No-code tools (Airtable, Glide)', category: 'Technical' },
  { name: 'Static site building', category: 'Technical' },
  { name: 'Accessibility (WCAG) auditing', category: 'Technical' },
  { name: 'Cybersecurity for nonprofits', category: 'Technical' },
  { name: 'Privacy / GDPR engineering', category: 'Technical' },
  { name: 'Self-hosting / sysadmin', category: 'Technical' },
  { name: 'Carbon accounting tools', category: 'Technical' },
  { name: 'Lifecycle assessment software', category: 'Technical' },
  { name: 'Web scraping', category: 'Technical' },
  { name: 'Network / graph analysis', category: 'Technical' },
  { name: 'AR / VR prototyping', category: 'Technical' },
  { name: 'uMap / Felt mapping', category: 'Technical' },
  { name: 'Open-source contribution', category: 'Technical' },
  { name: 'Tech support / digital inclusion', category: 'Technical' },
  { name: 'Hardware hacking', category: 'Technical' },
  { name: 'Documentation (technical)', category: 'Technical' },

  // ─── Legal ─────────────────────────────────────────────────
  { name: 'Charity / nonprofit law', category: 'Legal' },
  { name: 'Cooperative law', category: 'Legal' },
  { name: 'Community Benefit Society setup', category: 'Legal' },
  { name: 'Planning law', category: 'Legal' },
  { name: 'Environmental law', category: 'Legal' },
  { name: 'Housing law', category: 'Legal' },
  { name: 'Tenant rights advocacy', category: 'Legal' },
  { name: 'Land trust law', category: 'Legal' },
  { name: 'Intellectual property / Creative Commons', category: 'Legal' },
  { name: 'Data protection / GDPR advisory', category: 'Legal' },
  { name: 'Employment law (nonprofit)', category: 'Legal' },
  { name: 'Trustee / board governance', category: 'Legal' },
  { name: 'Constitution drafting', category: 'Legal' },
  { name: 'Bylaws drafting', category: 'Legal' },
  { name: 'Freedom of Information requests', category: 'Legal' },
  { name: 'Public procurement law', category: 'Legal' },
  { name: 'Charity tax / Gift Aid', category: 'Legal' },
  { name: 'Lobbying & advocacy compliance', category: 'Legal' },
  { name: 'Insurance & liability advisory', category: 'Legal' },
  { name: 'Trademark / branding protection', category: 'Legal' },
  { name: 'Safeguarding policy drafting', category: 'Legal' },

  // ─── Creative ──────────────────────────────────────────────
  { name: 'Illustration', category: 'Creative' },
  { name: 'Motion graphics / animation', category: 'Creative' },
  { name: 'Branding / identity systems', category: 'Creative' },
  { name: 'Typography', category: 'Creative' },
  { name: 'Zine / print publishing', category: 'Creative' },
  { name: 'Web design', category: 'Creative' },
  { name: 'Sound design', category: 'Creative' },
  { name: 'Music composition', category: 'Creative' },
  { name: 'Podcast production', category: 'Creative' },
  { name: 'Audio engineering', category: 'Creative' },
  { name: 'Wayfinding & signage', category: 'Creative' },
  { name: 'Murals / street art', category: 'Creative' },
  { name: 'Storytelling', category: 'Creative' },
  { name: 'Documentary filmmaking', category: 'Creative' },
  { name: 'Drone videography', category: 'Creative' },
  { name: 'Field recording', category: 'Creative' },
  { name: 'Event / stage design', category: 'Creative' },
  { name: 'Costume / wearables', category: 'Creative' },
  { name: 'Educational content design', category: 'Creative' },
  { name: 'Editorial / magazine design', category: 'Creative' },
  { name: 'Pattern design', category: 'Creative' },
  { name: 'Photo retouching', category: 'Creative' },
  { name: 'Colour & palette systems', category: 'Creative' },
  { name: 'Children’s book illustration', category: 'Creative' },
  { name: 'Map illustration', category: 'Creative' },
  { name: 'Voiceover & narration', category: 'Creative' },
  { name: 'Live event audio', category: 'Creative' },
  { name: 'Visual journalism', category: 'Creative' },

  // ─── Community ─────────────────────────────────────────────
  { name: 'Door-knocking / canvassing', category: 'Community' },
  { name: 'Public consultation design', category: 'Community' },
  { name: 'Workshop facilitation', category: 'Community' },
  { name: 'Conflict mediation', category: 'Community' },
  { name: 'Coalition building', category: 'Community' },
  { name: 'Mutual aid coordination', category: 'Community' },
  { name: 'Network weaving', category: 'Community' },
  { name: 'Peer support', category: 'Community' },
  { name: 'Mentoring / coaching', category: 'Community' },
  { name: 'Hosting open houses', category: 'Community' },
  { name: 'Neighbourhood mapping', category: 'Community' },
  { name: 'Asset-based community development', category: 'Community' },
  { name: 'Citizen science coordination', category: 'Community' },
  { name: 'Volunteer recruitment', category: 'Community' },
  { name: 'Resident engagement', category: 'Community' },
  { name: 'Cultural competence', category: 'Community' },
  { name: 'Youth work', category: 'Community' },
  { name: 'Elder engagement', category: 'Community' },
  { name: 'Newcomer & refugee support', category: 'Community' },
  { name: 'Disability inclusion practice', category: 'Community' },
  { name: 'Trauma-informed facilitation', category: 'Community' },
  { name: 'Restorative justice practice', category: 'Community' },
  { name: 'Phone banking / outreach', category: 'Community' },
  { name: 'Petition organising', category: 'Community' },
  { name: 'Block-club coordination', category: 'Community' },
  { name: 'Tenants’ association support', category: 'Community' },
  { name: 'Faith community liaison', category: 'Community' },
  { name: 'Indigenous partnership practice', category: 'Community' },
  { name: 'Anti-racism facilitation', category: 'Community' },
  { name: 'Care-coordination', category: 'Community' },
  { name: 'Allyship practice', category: 'Community' },
  { name: 'Peace circles / restorative dialogue', category: 'Community' },

  // ─── Finance & Operations ──────────────────────────────────
  { name: 'Bookkeeping', category: 'Finance & Operations' },
  { name: 'Treasury management', category: 'Finance & Operations' },
  { name: 'Budgeting', category: 'Finance & Operations' },
  { name: 'Cashflow forecasting', category: 'Finance & Operations' },
  { name: 'Audit preparation', category: 'Finance & Operations' },
  { name: 'Fundraising strategy', category: 'Finance & Operations' },
  { name: 'Donor stewardship', category: 'Finance & Operations' },
  { name: 'Crowdfunding campaigns', category: 'Finance & Operations' },
  { name: 'Membership management', category: 'Finance & Operations' },
  { name: 'CRM administration', category: 'Finance & Operations' },
  { name: 'HR / payroll', category: 'Finance & Operations' },
  { name: 'Recruitment', category: 'Finance & Operations' },
  { name: 'Onboarding design', category: 'Finance & Operations' },
  { name: 'Performance review design', category: 'Finance & Operations' },
  { name: 'Office / facilities management', category: 'Finance & Operations' },
  { name: 'Inventory management', category: 'Finance & Operations' },
  { name: 'Logistics planning', category: 'Finance & Operations' },
  { name: 'Risk register management', category: 'Finance & Operations' },
  { name: 'Compliance reporting', category: 'Finance & Operations' },
  { name: 'Impact reporting', category: 'Finance & Operations' },
  { name: 'Theory of change drafting', category: 'Finance & Operations' },
  { name: 'Monitoring & evaluation', category: 'Finance & Operations' },
  { name: 'Cost-benefit analysis', category: 'Finance & Operations' },
  { name: 'Share-offer administration', category: 'Finance & Operations' },
  { name: 'Co-op governance', category: 'Finance & Operations' },
  { name: 'Board secretariat', category: 'Finance & Operations' },
  { name: 'Tendering / bid writing', category: 'Finance & Operations' },
  { name: 'Equipment maintenance coordination', category: 'Finance & Operations' },
  { name: 'Health & safety planning', category: 'Finance & Operations' },
  { name: 'Insurance management', category: 'Finance & Operations' },
  { name: 'Time banking administration', category: 'Finance & Operations' },

  // ─── Communications ────────────────────────────────────────
  { name: 'Newsletter writing', category: 'Communications' },
  { name: 'Email marketing', category: 'Communications' },
  { name: 'Content strategy', category: 'Communications' },
  { name: 'Editorial planning', category: 'Communications' },
  { name: 'SEO basics', category: 'Communications' },
  { name: 'Press release writing', category: 'Communications' },
  { name: 'Crisis communications', category: 'Communications' },
  { name: 'Online community management', category: 'Communications' },
  { name: 'Internal communications', category: 'Communications' },
  { name: 'Advocacy storytelling', category: 'Communications' },
  { name: 'Plain-language writing', category: 'Communications' },
  { name: 'Technical writing', category: 'Communications' },
  { name: 'Grant report writing', category: 'Communications' },
  { name: 'Annual report production', category: 'Communications' },
  { name: 'Podcast hosting', category: 'Communications' },
  { name: 'Live streaming', category: 'Communications' },
  { name: 'Short-form video editing', category: 'Communications' },
  { name: 'Photography for socials', category: 'Communications' },
  { name: 'Multilingual content', category: 'Communications' },
  { name: 'Inclusive language editing', category: 'Communications' },
  { name: 'Speechwriting', category: 'Communications' },
  { name: 'Stakeholder mapping', category: 'Communications' },
  { name: 'Brand voice / guidelines', category: 'Communications' },
  { name: 'Webinar production', category: 'Communications' },
  { name: 'Influencer outreach', category: 'Communications' },
  { name: 'Investigative research', category: 'Communications' },
  { name: 'Campaign strategy', category: 'Communications' },
  { name: 'Policy briefing writing', category: 'Communications' },
  { name: 'Local government engagement', category: 'Communications' },
  { name: 'Parliamentary engagement', category: 'Communications' },
  { name: 'Climate negotiation knowledge', category: 'Communications' },
  { name: 'Direct action organising', category: 'Communications' },
  { name: 'Movement strategy', category: 'Communications' },
  { name: 'Letter-writing campaigns', category: 'Communications' },

  // ─── Science & Research ────────────────────────────────────
  { name: 'Botany / plant identification', category: 'Science & Research' },
  { name: 'Soil science', category: 'Science & Research' },
  { name: 'Hydrology / water systems', category: 'Science & Research' },
  { name: 'Marine biology', category: 'Science & Research' },
  { name: 'Ornithology / bird surveys', category: 'Science & Research' },
  { name: 'Entomology / pollinator surveys', category: 'Science & Research' },
  { name: 'Forestry', category: 'Science & Research' },
  { name: 'Agroecology', category: 'Science & Research' },
  { name: 'Permaculture design', category: 'Science & Research' },
  { name: 'Mycology', category: 'Science & Research' },
  { name: 'Air-quality science', category: 'Science & Research' },
  { name: 'Renewable energy engineering', category: 'Science & Research' },
  { name: 'Solar PV system design', category: 'Science & Research' },
  { name: 'Wind energy basics', category: 'Science & Research' },
  { name: 'Heat-pump knowledge', category: 'Science & Research' },
  { name: 'Energy efficiency assessment', category: 'Science & Research' },
  { name: 'Passivhaus design', category: 'Science & Research' },
  { name: 'Building retrofit', category: 'Science & Research' },
  { name: 'Urban planning', category: 'Science & Research' },
  { name: 'Landscape architecture', category: 'Science & Research' },
  { name: 'Transport planning', category: 'Science & Research' },
  { name: 'Civil engineering', category: 'Science & Research' },
  { name: 'Mechanical engineering', category: 'Science & Research' },
  { name: 'Electrical engineering', category: 'Science & Research' },
  { name: 'Structural engineering', category: 'Science & Research' },
  { name: 'Sustainable materials', category: 'Science & Research' },
  { name: 'Industrial ecology', category: 'Science & Research' },
  { name: 'Lifecycle assessment', category: 'Science & Research' },
  { name: 'Carbon accounting', category: 'Science & Research' },
  { name: 'Systems thinking', category: 'Science & Research' },
  { name: 'Qualitative research', category: 'Science & Research' },
  { name: 'Ethnographic research', category: 'Science & Research' },
  { name: 'Action research', category: 'Science & Research' },
  { name: 'Literature review', category: 'Science & Research' },
  { name: 'Survey design / methodology', category: 'Science & Research' },
  { name: 'Climate adaptation planning', category: 'Science & Research' },
  { name: 'Ecological restoration', category: 'Science & Research' },
  { name: 'Habitat mapping', category: 'Science & Research' },
  { name: 'Wildlife corridors / connectivity', category: 'Science & Research' },
  { name: 'Statistics', category: 'Science & Research' },

  // ─── Hands-on / Trades ─────────────────────────────────────
  { name: 'Carpentry', category: 'Hands-on / Trades' },
  { name: 'Plumbing', category: 'Hands-on / Trades' },
  { name: 'Electrical (qualified)', category: 'Hands-on / Trades' },
  { name: 'Masonry / bricklaying', category: 'Hands-on / Trades' },
  { name: 'Plastering', category: 'Hands-on / Trades' },
  { name: 'Painting & decorating', category: 'Hands-on / Trades' },
  { name: 'Tiling', category: 'Hands-on / Trades' },
  { name: 'Welding', category: 'Hands-on / Trades' },
  { name: 'Metalwork', category: 'Hands-on / Trades' },
  { name: 'Bike mechanics', category: 'Hands-on / Trades' },
  { name: 'Sewing & garment repair', category: 'Hands-on / Trades' },
  { name: 'Knitting / crochet', category: 'Hands-on / Trades' },
  { name: 'Upholstery', category: 'Hands-on / Trades' },
  { name: 'Woodworking', category: 'Hands-on / Trades' },
  { name: 'Tool sharpening', category: 'Hands-on / Trades' },
  { name: 'Furniture restoration', category: 'Hands-on / Trades' },
  { name: 'Small appliance repair', category: 'Hands-on / Trades' },
  { name: 'Electronics repair', category: 'Hands-on / Trades' },
  { name: 'Sewing machine maintenance', category: 'Hands-on / Trades' },
  { name: 'Cooking for crowds', category: 'Hands-on / Trades' },
  { name: 'Catering for events', category: 'Hands-on / Trades' },
  { name: 'Gardening / horticulture', category: 'Hands-on / Trades' },
  { name: 'Pruning & arboriculture', category: 'Hands-on / Trades' },
  { name: 'Composting (large-scale)', category: 'Hands-on / Trades' },
  { name: 'Beekeeping', category: 'Hands-on / Trades' },
  { name: 'Animal husbandry', category: 'Hands-on / Trades' },
  { name: 'Foraging', category: 'Hands-on / Trades' },
  { name: 'Preserving & canning', category: 'Hands-on / Trades' },
  { name: 'Fermenting', category: 'Hands-on / Trades' },
  { name: 'Solar PV installation', category: 'Hands-on / Trades' },
  { name: 'Insulation installation', category: 'Hands-on / Trades' },
  { name: 'Glazing / window repair', category: 'Hands-on / Trades' },
  { name: 'Roofing basics', category: 'Hands-on / Trades' },
  { name: 'Driving (van / minibus)', category: 'Hands-on / Trades' },

  // ─── Health & Wellbeing ────────────────────────────────────
  { name: 'Mental health first aid', category: 'Health & Wellbeing' },
  { name: 'Physical first aid', category: 'Health & Wellbeing' },
  { name: 'Disability support practice', category: 'Health & Wellbeing' },
  { name: 'Public health knowledge', category: 'Health & Wellbeing' },
  { name: 'Nutrition / food literacy', category: 'Health & Wellbeing' },
  { name: 'Yoga / movement instruction', category: 'Health & Wellbeing' },
  { name: 'Mindfulness facilitation', category: 'Health & Wellbeing' },
  { name: 'Childcare / playwork', category: 'Health & Wellbeing' },
  { name: 'Eldercare', category: 'Health & Wellbeing' },
  { name: 'Wellbeing facilitation', category: 'Health & Wellbeing' },
  { name: 'Peer counselling', category: 'Health & Wellbeing' },
  { name: 'Burnout / stress coaching', category: 'Health & Wellbeing' },
  { name: 'Harm reduction practice', category: 'Health & Wellbeing' },
  { name: 'Trauma support practice', category: 'Health & Wellbeing' },
  { name: 'Suicide prevention training', category: 'Health & Wellbeing' },
  { name: 'Cooking-for-health workshops', category: 'Health & Wellbeing' },
  { name: 'Birth / postnatal support', category: 'Health & Wellbeing' },

  // ─── Education ─────────────────────────────────────────────
  { name: 'Curriculum design', category: 'Education' },
  { name: 'Lesson plan writing', category: 'Education' },
  { name: 'Teaching young children', category: 'Education' },
  { name: 'Teaching teens', category: 'Education' },
  { name: 'Adult education / lifelong learning', category: 'Education' },
  { name: 'ESOL teaching', category: 'Education' },
  { name: 'STEM outreach', category: 'Education' },
  { name: 'Sustainability / climate education', category: 'Education' },
  { name: 'Outdoor / forest-school education', category: 'Education' },
  { name: 'Popular education / Freirean practice', category: 'Education' },
  { name: 'Tutoring / one-to-one teaching', category: 'Education' },
  { name: 'Training-the-trainer', category: 'Education' },
  { name: 'Educational evaluation', category: 'Education' },
  { name: 'Learning resources design', category: 'Education' },
  { name: 'Game-based learning design', category: 'Education' },
  { name: 'Inclusive classroom practice', category: 'Education' },
  { name: 'Educational technology', category: 'Education' },
  { name: 'Museum / heritage interpretation', category: 'Education' },
  { name: 'Library science', category: 'Education' },
  { name: 'Special educational needs (SEND)', category: 'Education' },
  { name: 'Storytime / reading aloud', category: 'Education' },
]

async function main() {
  const existingCount = await db.skill.count()
  console.log(`Skills in DB before: ${existingCount}`)
  console.log(`Upserting ${skills.length} skills…`)

  let inserted = 0
  let kept = 0
  for (const s of skills) {
    const result = await db.skill.upsert({
      where: { name: s.name },
      update: { category: s.category },
      create: { name: s.name, category: s.category },
    })
    // Crude: if the row's createdAt is newer than 5 seconds ago, count as inserted.
    // Better: just trust the count delta at the end.
    if (result) inserted++
  }

  const finalCount = await db.skill.count()
  kept = finalCount - existingCount
  console.log(`Skills in DB after:  ${finalCount} (+${kept})`)
  console.log(`Upsert operations: ${inserted}`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await db.$disconnect()
  })
