import type { Locale } from '@/lib/locale-shared'

/* ================================================================
   Message catalogs live in messages/<locale>/<namespace>.json.
   English is the authored source; other locales are generated by
   `npm run translate` (see docs/i18n-plan.md). A locale missing a
   namespace file falls back to the English one, so partially
   translated locales degrade to English rather than blank keys.
   ================================================================ */

/**
 * Every namespace that exists on disk for `en`. Append-only: each
 * phase-4 batch adds its namespace here in the same commit that
 * creates the catalog file.
 */
export const NAMESPACES = ['common', 'errors', 'steps'] as const

export type Namespace = (typeof NAMESPACES)[number]

/**
 * Which namespaces each route group's client provider ships to the
 * browser. Server components read the full catalog via
 * `getTranslations` at no client cost — this list only bounds the
 * client bundle. Unknown (not-yet-created) namespaces are simply
 * absent from the loaded messages and get filtered out.
 */
export const GROUP_NAMESPACES = {
  platform: [
    'common',
    'nav',
    'errors',
    'notifications',
    'search',
    'dashboard',
    'browse',
    'project',
    'steps',
    'blueprints',
    'orgs',
    'skillMatches',
    'mySteps',
    'myProjects',
    'messagesInbox',
    'profile',
    'users',
    'admin',
  ],
  public: ['common', 'nav', 'errors', 'browse', 'project', 'steps', 'blueprints', 'orgs', 'users', 'search'],
  marketing: ['common', 'nav'],
  auth: ['common', 'auth'],
  // Legal pages are fully server-rendered; the shared chrome (navbar
  // with the language switcher) is the only client consumer.
  legal: ['common', 'nav'],
} as const satisfies Record<string, readonly string[]>

type MessageTree = { [key: string]: string | MessageTree }

async function loadNamespace(locale: string, ns: string): Promise<MessageTree | null> {
  try {
    return (await import(`../messages/${locale}/${ns}.json`)).default as MessageTree
  } catch {
    return null
  }
}

/** Load the full catalog for a locale, falling back to English per namespace. */
export async function loadMessages(locale: Locale): Promise<Record<string, MessageTree>> {
  const entries = await Promise.all(
    NAMESPACES.map(async (ns) => {
      const own = locale === 'en' ? null : await loadNamespace(locale, ns)
      return [ns, own ?? (await loadNamespace('en', ns)) ?? {}] as const
    }),
  )
  return Object.fromEntries(entries)
}

/** Subset a loaded catalog to the namespaces a client provider ships. */
export function pickMessages<T extends Record<string, MessageTree>>(
  messages: T,
  namespaces: readonly string[],
): Record<string, MessageTree> {
  const subset: Record<string, MessageTree> = {}
  for (const ns of namespaces) {
    if (ns in messages) subset[ns] = messages[ns]
  }
  return subset
}
